CREATE TYPE "status_orcamento" AS ENUM (
  'PENDENTE',
  'APROVADO',
  'RECUSADO'
)

CREATE TYPE "grupo_item" AS ENUM (
  'FLUIDOS',
  'FILTROS',
  'FREIOS',
  'MOTOR',
  'INJECAO',
  'SUSPENSAO',
  'ELETRICA',
  'TRANSMISSAO',
  'SERVICOS'
)

CREATE TYPE "fonte_preco" AS ENUM (
  'MANUAL',
  'HISTORICO',
  'EXTERNO'
)

CREATE TYPE "tipo_item" AS ENUM (
  'PECA',
  'MAO_OBRA'
)

CREATE TYPE "tipo_alerta" AS ENUM (
  'TROCA_RECENTE',
  'PRECO_ACIMA_MEDIA',
  'MAO_OBRA_ALTA',
  'ITEM_DUPLICADO',
  'ITEM_GENERICO',
  'CONSUMIVEL_CARO',
  'VALOR_ZERADO'
)

CREATE TYPE "severidade_alerta" AS ENUM (
  'ALTA',
  'MEDIA',
  'BAIXA'
)

CREATE TYPE "tipo_manutencao" AS ENUM (
  'PREVENTIVA',
  'CORRETIVA',
  'PREDITIVA'
)

CREATE TYPE "status_manutencao" AS ENUM (
  'EM_ANDAMENTO',
  'CONCLUIDA'
)

CREATE TABLE "precos_referencia" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_categoria" integer NOT NULL,
  "codigo_peca" varchar(50),
  "descricao" varchar(255) NOT NULL,
  "valor_min" numeric(10,2) NOT NULL,
  "valor_max" numeric(10,2) NOT NULL,
  "fonte" fonte_preco NOT NULL DEFAULT 'MANUAL',
  "amostras" integer NOT NULL DEFAULT 1,
  "atualizado_em" timestamptz NOT NULL DEFAULT (now())
)

CREATE TABLE "usuarios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "senha_hash" varchar(255) NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT (now())
)

CREATE TABLE "veiculos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer NOT NULL,
  "marca" varchar(50) NOT NULL,
  "modelo" varchar(80) NOT NULL,
  "motor" varchar(30),
  "placa" varchar(10),
  "ano_fabricacao" smallint NOT NULL,
  "ano_modelo" smallint,
  "km_atual" integer NOT NULL DEFAULT 0,
  "criado_em" timestamptz NOT NULL DEFAULT (now())
)

CREATE TABLE "oficinas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(120) NOT NULL,
  "cidade" varchar(80),
  "telefone" varchar(20),
  "criado_em" timestamptz NOT NULL DEFAULT (now())
)

CREATE TABLE "orcamentos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_veiculo" integer NOT NULL,
  "id_oficina" integer NOT NULL,
  "data_emissao" date NOT NULL,
  "km" integer NOT NULL,
  "status" status_orcamento NOT NULL DEFAULT 'PENDENTE',
  "arquivo_url" varchar(255),
  "texto_extraido" text,
  "criado_em" timestamptz NOT NULL DEFAULT (now())
)

CREATE TABLE "categorias_item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100) UNIQUE NOT NULL,
  "grupo" grupo_item NOT NULL,
  "intervalo_km" integer,
  "intervalo_meses" integer
)

CREATE TABLE "itens_orcamento" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_orcamento" integer NOT NULL,
  "id_categoria" integer NOT NULL,
  "descricao" varchar(255) NOT NULL,
  "tipo" tipo_item NOT NULL,
  "quantidade" numeric(10,2) NOT NULL DEFAULT 1,
  "valor_unitario" numeric(10,2) NOT NULL
)

CREATE TABLE "alertas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_orcamento" integer NOT NULL,
  "id_item" integer,
  "tipo" tipo_alerta NOT NULL,
  "severidade" severidade_alerta NOT NULL,
  "mensagem" varchar(255) NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT (now())
)

CREATE TABLE "manutencoes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_orcamento" integer UNIQUE NOT NULL,
  "data" date NOT NULL,
  "km" integer NOT NULL,
  "tipo" tipo_manutencao NOT NULL,
  "status" status_manutencao NOT NULL DEFAULT 'CONCLUIDA',
  "criado_em" timestamptz NOT NULL DEFAULT (now())
)

CREATE INDEX ON "precos_referencia" ("id_categoria")

CREATE INDEX ON "precos_referencia" ("codigo_peca")

CREATE UNIQUE INDEX ON "precos_referencia" ("id_categoria", "codigo_peca", "fonte")

CREATE INDEX ON "veiculos" ("id_usuario")

CREATE INDEX ON "orcamentos" ("id_veiculo")

CREATE INDEX ON "orcamentos" ("id_oficina")

CREATE INDEX ON "orcamentos" ("id_veiculo", "data_emissao")

CREATE INDEX ON "itens_orcamento" ("id_orcamento")

CREATE INDEX ON "itens_orcamento" ("id_categoria")

CREATE INDEX ON "alertas" ("id_orcamento")

COMMENT ON TABLE "precos_referencia" IS 'valor_min <= valor_max (CHECK na migração). Unique exige NULLS NOT DISTINCT no PG15+'

COMMENT ON TABLE "orcamentos" IS 'Valor total NÃO é guardado: é calculado pela soma dos itens'

COMMENT ON COLUMN "orcamentos"."arquivo_url" IS 'Foto/PDF enviado (nulo se lançado manualmente)'

COMMENT ON COLUMN "orcamentos"."texto_extraido" IS 'Retorno da IA, guardado para não pagar a extração duas vezes'

COMMENT ON COLUMN "categorias_item"."intervalo_km" IS 'Nulo = sem intervalo (ex.: mão de obra)'

COMMENT ON COLUMN "itens_orcamento"."descricao" IS 'Texto original escrito pela oficina'

COMMENT ON COLUMN "alertas"."id_item" IS 'Nulo = alerta do orçamento inteiro (ex.: mão de obra alta)'

COMMENT ON COLUMN "manutencoes"."id_orcamento" IS 'unique = 1 orçamento gera no máximo 1 manutenção'

ALTER TABLE "precos_referencia" ADD FOREIGN KEY ("id_categoria") REFERENCES "categorias_item" ("id") DEFERRABLE INITIALLY IMMEDIATE

ALTER TABLE "veiculos" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuarios" ("id") DEFERRABLE INITIALLY IMMEDIATE

ALTER TABLE "orcamentos" ADD FOREIGN KEY ("id_veiculo") REFERENCES "veiculos" ("id") DEFERRABLE INITIALLY IMMEDIATE

ALTER TABLE "orcamentos" ADD FOREIGN KEY ("id_oficina") REFERENCES "oficinas" ("id") DEFERRABLE INITIALLY IMMEDIATE

ALTER TABLE "itens_orcamento" ADD FOREIGN KEY ("id_orcamento") REFERENCES "orcamentos" ("id") DEFERRABLE INITIALLY IMMEDIATE

ALTER TABLE "itens_orcamento" ADD FOREIGN KEY ("id_categoria") REFERENCES "categorias_item" ("id") DEFERRABLE INITIALLY IMMEDIATE

ALTER TABLE "alertas" ADD FOREIGN KEY ("id_orcamento") REFERENCES "orcamentos" ("id") DEFERRABLE INITIALLY IMMEDIATE

ALTER TABLE "alertas" ADD FOREIGN KEY ("id_item") REFERENCES "itens_orcamento" ("id") DEFERRABLE INITIALLY IMMEDIATE

ALTER TABLE "manutencoes" ADD FOREIGN KEY ("id_orcamento") REFERENCES "orcamentos" ("id") DEFERRABLE INITIALLY IMMEDIATE
