
BEGIN

-- ENUMS
CREATE TYPE status_orcamento  AS ENUM ('PENDENTE','APROVADO','RECUSADO')
CREATE TYPE grupo_item        AS ENUM ('FLUIDOS','FILTROS','FREIOS','MOTOR','INJECAO','SUSPENSAO','ELETRICA','TRANSMISSAO','SERVICOS')
CREATE TYPE fonte_preco       AS ENUM ('MANUAL','HISTORICO','EXTERNO')
CREATE TYPE tipo_item         AS ENUM ('PECA','MAO_OBRA')
CREATE TYPE tipo_alerta       AS ENUM ('TROCA_RECENTE','PRECO_ACIMA_MEDIA','MAO_OBRA_ALTA','ITEM_DUPLICADO','ITEM_GENERICO','CONSUMIVEL_CARO','VALOR_ZERADO')
CREATE TYPE severidade_alerta AS ENUM ('ALTA','MEDIA','BAIXA')
CREATE TYPE tipo_manutencao   AS ENUM ('PREVENTIVA','CORRETIVA','PREDITIVA')
CREATE TYPE status_manutencao AS ENUM ('EM_ANDAMENTO','CONCLUIDA')

-- TABELAS
CREATE TABLE usuarios (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome        varchar(100) NOT NULL,
  email       varchar(150) NOT NULL UNIQUE,
  senha_hash  varchar(255) NOT NULL,
  criado_em   timestamptz  NOT NULL DEFAULT now()
)
CREATE TABLE veiculos (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario      integer     NOT NULL REFERENCES usuarios(id),
  marca           varchar(50) NOT NULL,
  modelo          varchar(80) NOT NULL,
  motor           varchar(30),
  placa           varchar(10),
  ano_fabricacao  smallint    NOT NULL,
  ano_modelo      smallint,
  km_atual        integer     NOT NULL DEFAULT 0 CHECK (km_atual >= 0),
  criado_em       timestamptz NOT NULL DEFAULT now()
)
CREATE INDEX ix_veiculos_usuario ON veiculos (id_usuario)

CREATE TABLE oficinas (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome       varchar(120) NOT NULL,
  cidade     varchar(80),
  telefone   varchar(20),
  criado_em  timestamptz NOT NULL DEFAULT now()
)

CREATE TABLE orcamentos (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_veiculo      integer          NOT NULL REFERENCES veiculos(id),
  id_oficina      integer          NOT NULL REFERENCES oficinas(id),
  data_emissao    date             NOT NULL,
  km              integer          NOT NULL CHECK (km >= 0),
  status          status_orcamento NOT NULL DEFAULT 'PENDENTE',
  arquivo_url     varchar(255),
  texto_extraido  text,
  criado_em       timestamptz      NOT NULL DEFAULT now()
)
CREATE INDEX ix_orcamentos_veiculo      ON orcamentos (id_veiculo)
CREATE INDEX ix_orcamentos_oficina      ON orcamentos (id_oficina)
CREATE INDEX ix_orcamentos_veiculo_data ON orcamentos (id_veiculo, data_emissao)

CREATE TABLE categorias_item (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome             varchar(100) NOT NULL UNIQUE,
  grupo            grupo_item   NOT NULL,
  intervalo_km     integer,
  intervalo_meses  integer
)

CREATE TABLE precos_referencia (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_categoria  integer       NOT NULL REFERENCES categorias_item(id),
  codigo_peca   varchar(50),
  descricao     varchar(255)  NOT NULL,
  valor_min     numeric(10,2) NOT NULL,
  valor_max     numeric(10,2) NOT NULL,
  fonte         fonte_preco   NOT NULL DEFAULT 'MANUAL',
  amostras      integer       NOT NULL DEFAULT 1,
  atualizado_em timestamptz   NOT NULL DEFAULT now(),
  CONSTRAINT ck_precos_ref_faixa    CHECK (valor_min >= 0 AND valor_min <= valor_max),
  CONSTRAINT ck_precos_ref_amostras CHECK (amostras >= 1)
)
CREATE INDEX ix_precos_ref_categoria ON precos_referencia (id_categoria)
CREATE INDEX ix_precos_ref_codigo    ON precos_referencia (codigo_peca)
CREATE UNIQUE INDEX ux_precos_ref_categoria_codigo_fonte
  ON precos_referencia (id_categoria, COALESCE(codigo_peca, ''), fonte)

CREATE TABLE itens_orcamento (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orcamento    integer       NOT NULL REFERENCES orcamentos(id),
  id_categoria    integer       NOT NULL REFERENCES categorias_item(id),
  descricao       varchar(255)  NOT NULL,
  tipo            tipo_item     NOT NULL,
  quantidade      numeric(10,2) NOT NULL DEFAULT 1 CHECK (quantidade > 0),
  valor_unitario  numeric(10,2) NOT NULL CHECK (valor_unitario >= 0)
)
CREATE INDEX ix_itens_orcamento ON itens_orcamento (id_orcamento)
CREATE INDEX ix_itens_categoria ON itens_orcamento (id_categoria)

CREATE TABLE alertas (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orcamento  integer           NOT NULL REFERENCES orcamentos(id),
  id_item       integer           REFERENCES itens_orcamento(id),
  tipo          tipo_alerta       NOT NULL,
  severidade    severidade_alerta NOT NULL,
  mensagem      varchar(255)      NOT NULL,
  criado_em     timestamptz       NOT NULL DEFAULT now()
)
CREATE INDEX ix_alertas_orcamento ON alertas (id_orcamento)

CREATE TABLE manutencoes (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orcamento  integer           NOT NULL UNIQUE REFERENCES orcamentos(id),
  data          date              NOT NULL,
  km            integer           NOT NULL,
  tipo          tipo_manutencao   NOT NULL,
  status        status_manutencao NOT NULL DEFAULT 'CONCLUIDA',
  criado_em     timestamptz       NOT NULL DEFAULT now()
)
-- DADOS: USUÁRIOS
INSERT INTO usuarios (id, nome, email, senha_hash) VALUES
(1, 'Carlos Mendes',  'carlos.mendes@email.com',  '$2b$12$PLACEHOLDER.gerar.pela.aplicacao.0000000000000000000'),
(2, 'Ana Ribeiro',    'ana.ribeiro@email.com',    '$2b$12$PLACEHOLDER.gerar.pela.aplicacao.0000000000000000000'),
(3, 'Marcos Teixeira','marcos.teixeira@email.com','$2b$12$PLACEHOLDER.gerar.pela.aplicacao.0000000000000000000')

-- DADOS: VEÍCULOS 
INSERT INTO veiculos (id, id_usuario, marca, modelo, motor, placa, ano_fabricacao, ano_modelo, km_atual) VALUES
(1, 1, 'Volkswagen', 'Gol',     '1.0 MPI',       'QWE1A23', 2018, 2018,  98000),
(2, 1, 'Chevrolet',  'Onix',    '1.0 Turbo',     'RTY2B34', 2022, 2023,  41000),
(3, 2, 'Hyundai',    'HB20',    '1.0 Aspirado',  'UIO3C45', 2020, 2020,  68000),
(4, 2, 'Fiat',       'Strada',  '1.4 Fire',      'PAS4D56', 2021, 2021,  74000),
(5, 3, 'Toyota',     'Corolla', '2.0 Flex',      'DFG5E67', 2019, 2019, 105000),
(6, 3, 'Jeep',       'Compass', '2.0 Turbodiesel','HJK6F78', 2021, 2021,  88000)

-- DADOS: OFICINAS
INSERT INTO oficinas (id, nome, cidade, telefone) VALUES
(1, 'Auto Center Primavera',     'Campinas',  '(19) 3201-1001'),
(2, 'Mecânica Boa Viagem',       'Campinas',  '(19) 99811-2002'),
(3, 'Oficina Express Car',       'Campinas',  '(19) 3302-3003'),
(4, 'Concessionária Rede Norte', 'Campinas',  '(19) 3403-4004'),
(5, 'Garagem do Paulo',          'Sumaré',    '(19) 99722-5005')

-- DADOS: CATEGORIAS
INSERT INTO categorias_item (id, nome, grupo, intervalo_km, intervalo_meses) VALUES
(1,  'Óleo do motor semissintético', 'FLUIDOS',     10000, 12),
(2,  'Óleo do motor sintético',      'FLUIDOS',     10000, 12),
(3,  'Fluido de freio',              'FLUIDOS',     NULL,  24),
(4,  'Líquido de arrefecimento',     'FLUIDOS',     40000, 24),
(5,  'Óleo de câmbio',               'TRANSMISSAO', 60000, NULL),
(6,  'Filtro de óleo',               'FILTROS',     10000, 12),
(7,  'Filtro de ar do motor',        'FILTROS',     15000, 12),
(8,  'Filtro de combustível',        'FILTROS',     20000, 12),
(9,  'Filtro de cabine',             'FILTROS',     15000, 12),
(10, 'Pastilha de freio',            'FREIOS',      30000, NULL),
(11, 'Disco de freio',               'FREIOS',      60000, NULL),
(12, 'Lona de freio traseira',       'FREIOS',      50000, NULL),
(13, 'Kit correia dentada',          'MOTOR',       50000, 48),
(14, 'Correia auxiliar',             'MOTOR',       40000, NULL),
(15, 'Velas de ignição',             'MOTOR',       30000, NULL),
(16, 'Bobina de ignição',            'MOTOR',       NULL,  NULL),
(17, 'Bomba d''água',                'MOTOR',       50000, NULL),
(18, 'Bico injetor flex',            'INJECAO',     NULL,  NULL),
(19, 'Bico injetor diesel',          'INJECAO',     NULL,  NULL),
(20, 'Sonda lambda',                 'INJECAO',     80000, NULL),
(21, 'Amortecedor',                  'SUSPENSAO',   60000, NULL),
(22, 'Bieleta',                      'SUSPENSAO',   40000, NULL),
(23, 'Pivô de suspensão',            'SUSPENSAO',   60000, NULL),
(24, 'Alinhamento e balanceamento',  'SUSPENSAO',   10000, 12),
(25, 'Bateria',                      'ELETRICA',    NULL,  36),
(26, 'Lâmpada',                      'ELETRICA',    NULL,  NULL),
(27, 'Kit embreagem',                'TRANSMISSAO', NULL,  NULL),
(28, 'Mão de obra',                  'SERVICOS',    NULL,  NULL),
(29, 'Material de consumo/diversos', 'SERVICOS',    NULL,  NULL),
(30, 'Diagnóstico com scanner',      'SERVICOS',    NULL,  NULL)

-- DADOS: PREÇOS DE REFERÊNCIA (MANUAL)
INSERT INTO precos_referencia (id, id_categoria, descricao, valor_min, valor_max, fonte) VALUES
(1,  1,  'Óleo semissintético (litro)',       30.00,   45.00, 'MANUAL'),
(2,  2,  'Óleo sintético (litro)',            50.00,   80.00, 'MANUAL'),
(3,  6,  'Filtro de óleo (leve e diesel)',    25.00,   90.00, 'MANUAL'),
(4,  10, 'Pastilha de freio dianteira (jogo)',120.00, 200.00, 'MANUAL'),
(5,  13, 'Kit correia dentada + tensor',      350.00, 500.00, 'MANUAL'),
(6,  17, 'Bomba d''água',                     200.00, 320.00, 'MANUAL'),
(7,  19, 'Bico injetor diesel (unidade)',     900.00,1200.00, 'MANUAL'),
(8,  21, 'Amortecedor dianteiro (unidade)',   250.00, 400.00, 'MANUAL'),
(9,  25, 'Bateria 50-60Ah',                   420.00, 520.00, 'MANUAL'),
(10, 27, 'Kit embreagem (platô, disco, rolamento)', 750.00, 950.00, 'MANUAL')

--DADOS: ORÇAMENTOS
INSERT INTO orcamentos (id, id_veiculo, id_oficina, data_emissao, km, status, arquivo_url, texto_extraido) VALUES
-- Gol: revisão + 2 orçamentos concorrentes de correia
(1,  1, 1, '2025-11-10',  90000, 'APROVADO', 'uploads/2025/orc_0001.jpg', 'Revisão: óleo 5W30, filtros de óleo, ar e combustível, mão de obra.'),
(2,  1, 2, '2026-09-15',  97800, 'PENDENTE', 'uploads/2026/orc_0002.jpg', 'Kit correia dentada, bomba d''água, arrefecimento, mão de obra.'),
(3,  1, 3, '2026-09-20',  97900, 'RECUSADO', 'uploads/2026/orc_0003.jpg', 'Kit correia, bomba d''água, bomba d''água, material diverso, arrefecimento, mão de obra.'),
-- Onix: revisão, troca repetida e manutenção preditiva
(4,  2, 4, '2026-04-05',  35000, 'APROVADO', 'uploads/2026/orc_0004.pdf', 'Revisão programada: óleo 0W20, filtros de óleo, ar e cabine.'),
(5,  2, 5, '2026-06-01',  37200, 'RECUSADO', 'uploads/2026/orc_0005.jpg', 'Troca de óleo 0W20, filtro de óleo, mão de obra.'),
(14, 2, 4, '2026-09-10',  40500, 'APROVADO', 'uploads/2026/orc_0014.pdf', 'Teste de carga indicou bateria no fim da vida útil. Substituição.'),
-- HB20: freios e suspensão
(6,  3, 1, '2026-02-10',  62000, 'APROVADO', 'uploads/2026/orc_0006.jpg', 'Pastilhas, discos dianteiros, fluido DOT4, mão de obra.'),
(7,  3, 2, '2026-08-22',  67500, 'APROVADO', 'uploads/2026/orc_0007.jpg', 'Amortecedores dianteiros, bieletas, alinhamento, mão de obra.'),
-- Strada: 2 orçamentos concorrentes de embreagem
(8,  4, 3, '2026-07-14',  72000, 'PENDENTE', 'uploads/2026/orc_0008.jpg', 'Kit embreagem, óleo de câmbio, estopa/graxa, mão de obra.'),
(9,  4, 5, '2026-07-18',  72100, 'PENDENTE', 'uploads/2026/orc_0009.jpg', 'Kit embreagem, óleo de câmbio, mão de obra.'),
-- Corolla: revisão de 100 mil e orçamento manual
(10, 5, 4, '2026-03-03', 100000, 'APROVADO', 'uploads/2026/orc_0010.pdf', 'Revisão 100 mil km: óleo, filtros, velas iridium, fluidos.'),
(11, 5, 1, '2026-09-28', 104800, 'PENDENTE', NULL, NULL),
-- Compass diesel: revisão e bicos
(12, 6, 4, '2026-05-12',  80000, 'APROVADO', 'uploads/2026/orc_0012.pdf', 'Revisão diesel: óleo 5W30, filtros de óleo, combustível, ar e cabine.'),
(13, 6, 2, '2026-09-30',  87900, 'PENDENTE', 'uploads/2026/orc_0013.jpg', 'Bicos injetores diesel (4), diagnóstico, mão de obra.')

-- DADOS: ITENS
INSERT INTO itens_orcamento (id, id_orcamento, id_categoria, descricao, tipo, quantidade, valor_unitario) VALUES
-- #1 Gol revisão = R$ 357,00
(1,  1, 1,  'Óleo 5W30 semissintético (litro)',     'PECA',     4,     38.00),
(2,  1, 6,  'Filtro de óleo',                       'PECA',     1,     32.00),
(3,  1, 7,  'Filtro de ar do motor',                'PECA',     1,     45.00),
(4,  1, 8,  'Filtro de combustível',                'PECA',     1,     38.00),
(5,  1, 28, 'Mão de obra revisão',                  'MAO_OBRA', 1,     90.00),
-- #2 Gol correia (concorrente barato) = R$ 1.114,00
(6,  2, 13, 'Kit correia dentada + tensor',         'PECA',     1,    420.00),
(7,  2, 17, 'Bomba d''água',                        'PECA',     1,    260.00),
(8,  2, 4,  'Líquido de arrefecimento (litro)',     'PECA',     3,     28.00),
(9,  2, 28, 'Mão de obra correia e bomba d''água',  'MAO_OBRA', 1,    350.00),
-- #3 Gol correia (concorrente caro + duplicado + genérico) = R$ 2.146,00
(10, 3, 13, 'Kit correia dentada + tensor',         'PECA',     1,    690.00),
(11, 3, 17, 'Bomba d''água',                        'PECA',     1,    380.00),
(12, 3, 17, 'Bomba d''água',                        'PECA',     1,    380.00),
(13, 3, 29, 'Material diverso',                     'PECA',     1,    150.00),
(14, 3, 4,  'Líquido de arrefecimento (litro)',     'PECA',     3,     32.00),
(15, 3, 28, 'Mão de obra correia e bomba d''água',  'MAO_OBRA', 1,    450.00),
-- #4 Onix revisão = R$ 713,00
(16, 4, 2,  'Óleo 0W20 sintético (litro)',          'PECA',     4,     62.00),
(17, 4, 6,  'Filtro de óleo',                       'PECA',     1,     48.00),
(18, 4, 7,  'Filtro de ar do motor',                'PECA',     1,     72.00),
(19, 4, 9,  'Filtro de cabine',                     'PECA',     1,     65.00),
(20, 4, 28, 'Mão de obra revisão programada',       'MAO_OBRA', 1,    280.00),
-- #5 Onix troca repetida + mão de obra alta = R$ 685,00
(21, 5, 2,  'Óleo 0W20 sintético (litro)',          'PECA',     4,     70.00),
(22, 5, 6,  'Filtro de óleo',                       'PECA',     1,     55.00),
(23, 5, 28, 'Mão de obra troca de óleo',            'MAO_OBRA', 1,    350.00),
-- #6 HB20 freios = R$ 730,00
(24, 6, 10, 'Pastilha de freio dianteira (jogo)',   'PECA',     1,    165.00),
(25, 6, 11, 'Disco de freio dianteiro',             'PECA',     2,    185.00),
(26, 6, 3,  'Fluido de freio DOT4 500ml',           'PECA',     1,     35.00),
(27, 6, 28, 'Mão de obra sistema de freios',        'MAO_OBRA', 1,    160.00),
-- #7 HB20 suspensão = R$ 1.180,00
(28, 7, 21, 'Amortecedor dianteiro',                'PECA',     2,    340.00),
(29, 7, 22, 'Bieleta dianteira',                    'PECA',     2,     75.00),
(30, 7, 24, 'Alinhamento e balanceamento',          'MAO_OBRA', 1,    110.00),
(31, 7, 28, 'Mão de obra suspensão',                'MAO_OBRA', 1,    240.00),
-- #8 Strada embreagem (concorrente caro + consumível caro) = R$ 1.780,00
(32, 8, 27, 'Kit embreagem (platô, disco, rolamento)','PECA',   1,    980.00),
(33, 8, 5,  'Óleo de câmbio 75W80 (litro)',         'PECA',     2,     65.00),
(34, 8, 29, 'Estopa, graxa e desengripante',        'PECA',     1,    120.00),
(35, 8, 28, 'Mão de obra troca de embreagem',       'MAO_OBRA', 1,    550.00),
-- #9 Strada embreagem (concorrente barato) = R$ 1.446,00
(36, 9, 27, 'Kit embreagem (platô, disco, rolamento)','PECA',   1,    850.00),
(37, 9, 5,  'Óleo de câmbio 75W80 (litro)',         'PECA',     2,     58.00),
(38, 9, 28, 'Mão de obra troca de embreagem',       'MAO_OBRA', 1,    480.00),
-- #10 Corolla revisão 100 mil = R$ 1.448,00
(39, 10, 2,  'Óleo 0W20 sintético (litro)',         'PECA',     4.20,  65.00),
(40, 10, 6,  'Filtro de óleo',                      'PECA',     1,     55.00),
(41, 10, 7,  'Filtro de ar do motor',               'PECA',     1,     95.00),
(42, 10, 9,  'Filtro de cabine',                    'PECA',     1,     80.00),
(43, 10, 15, 'Vela de ignição iridium',             'PECA',     4,     85.00),
(44, 10, 4,  'Líquido de arrefecimento (litro)',    'PECA',     4,     35.00),
(45, 10, 3,  'Fluido de freio DOT4 500ml',          'PECA',     1,     45.00),
(46, 10, 28, 'Mão de obra revisão 100 mil km',      'MAO_OBRA', 1,    420.00),
-- #11 Corolla manual (preço acima da referência + valor zerado) = R$ 750,00
(47, 11, 25, 'Bateria 60Ah',                        'PECA',     1,    590.00),
(48, 11, 26, 'Lâmpada farol H11 (par)',             'PECA',     1,      0.00),
(49, 11, 30, 'Diagnóstico com scanner',             'MAO_OBRA', 1,    120.00),
(50, 11, 28, 'Mão de obra instalação',              'MAO_OBRA', 1,     40.00),
-- #12 Compass revisão diesel = R$ 1.345,00
(51, 12, 2,  'Óleo 5W30 sintético diesel (litro)',  'PECA',     6,     75.00),
(52, 12, 6,  'Filtro de óleo diesel',               'PECA',     1,     85.00),
(53, 12, 8,  'Filtro de combustível diesel',        'PECA',     1,    210.00),
(54, 12, 7,  'Filtro de ar do motor',               'PECA',     1,    130.00),
(55, 12, 9,  'Filtro de cabine',                    'PECA',     1,     90.00),
(56, 12, 28, 'Mão de obra revisão',                 'MAO_OBRA', 1,    380.00),
-- #13 Compass bicos (preço acima da referência) = R$ 6.750,00
(57, 13, 19, 'Bico injetor diesel',                 'PECA',     4,   1500.00),
(58, 13, 30, 'Diagnóstico com scanner',             'MAO_OBRA', 1,    150.00),
(59, 13, 28, 'Mão de obra substituição dos bicos',  'MAO_OBRA', 1,    600.00),
-- #14 Onix preditiva = R$ 540,00
(60, 14, 30, 'Teste de carga da bateria',           'MAO_OBRA', 1,     60.00),
(61, 14, 25, 'Bateria 50Ah',                        'PECA',     1,    480.00)

-- DADOS: ALERTAS
INSERT INTO alertas (id, id_orcamento, id_item, tipo, severidade, mensagem) VALUES
(1,  3,  10,   'PRECO_ACIMA_MEDIA', 'ALTA',  'Kit correia R$ 690,00 — 64% acima do orçamento concorrente #2 (R$ 420,00).'),
(2,  3,  11,   'PRECO_ACIMA_MEDIA', 'ALTA',  'Bomba d''água R$ 380,00 — 46% acima do orçamento concorrente #2 (R$ 260,00).'),
(3,  3,  12,   'ITEM_DUPLICADO',    'ALTA',  'Bomba d''água lançada duas vezes (itens #11 e #12).'),
(4,  3,  13,   'ITEM_GENERICO',     'MEDIA', '"Material diverso" sem especificação. Solicite a discriminação dos itens.'),
(5,  5,  21,   'TROCA_RECENTE',     'ALTA',  'Óleo trocado há 2.200 km (orçamento #4, 35.000 km). Intervalo recomendado: 10.000 km.'),
(6,  5,  22,   'TROCA_RECENTE',     'ALTA',  'Filtro de óleo trocado há 2.200 km (orçamento #4). Intervalo recomendado: 10.000 km.'),
(7,  5,  NULL, 'MAO_OBRA_ALTA',     'MEDIA', 'Mão de obra representa 51% do valor total do orçamento.'),
(8,  8,  32,   'PRECO_ACIMA_MEDIA', 'MEDIA', 'Kit embreagem R$ 980,00 — 15% acima do orçamento concorrente #9 (R$ 850,00).'),
(9,  8,  34,   'CONSUMIVEL_CARO',   'BAIXA', 'Consumíveis de R$ 120,00 acima do esperado (até R$ 30,00).'),
(10, 11, 47,   'PRECO_ACIMA_MEDIA', 'MEDIA', 'Bateria R$ 590,00 — 13% acima do teto de referência (R$ 520,00).'),
(11, 11, 48,   'VALOR_ZERADO',      'ALTA',  'Item "Lâmpada farol H11 (par)" com valor R$ 0,00. Confirme se será fornecido pelo cliente.'),
(12, 13, 57,   'PRECO_ACIMA_MEDIA', 'ALTA',  'Bico injetor diesel R$ 1.500,00 — 25% acima do teto de referência (R$ 1.200,00).')

-- DADOS: MANUTENÇÕES (só de orçamentos APROVADOS)
INSERT INTO manutencoes (id, id_orcamento, data, km, tipo, status) VALUES
(1, 1,  '2025-11-10',  90000, 'PREVENTIVA', 'CONCLUIDA'),
(2, 4,  '2026-04-05',  35000, 'PREVENTIVA', 'CONCLUIDA'),
(3, 6,  '2026-02-10',  62000, 'CORRETIVA',  'CONCLUIDA'),
(4, 7,  '2026-08-22',  67500, 'CORRETIVA',  'EM_ANDAMENTO'),
(5, 10, '2026-03-03', 100000, 'PREVENTIVA', 'CONCLUIDA'),
(6, 12, '2026-05-12',  80000, 'PREVENTIVA', 'CONCLUIDA'),
(7, 14, '2026-09-10',  40500, 'PREDITIVA',  'CONCLUIDA')

-- AJUSTE DAS SEQUENCES
SELECT setval(pg_get_serial_sequence('usuarios',          'id'), (SELECT MAX(id) FROM usuarios))
SELECT setval(pg_get_serial_sequence('veiculos',          'id'), (SELECT MAX(id) FROM veiculos))
SELECT setval(pg_get_serial_sequence('oficinas',          'id'), (SELECT MAX(id) FROM oficinas))
SELECT setval(pg_get_serial_sequence('categorias_item',   'id'), (SELECT MAX(id) FROM categorias_item))
SELECT setval(pg_get_serial_sequence('precos_referencia', 'id'), (SELECT MAX(id) FROM precos_referencia))
SELECT setval(pg_get_serial_sequence('orcamentos',        'id'), (SELECT MAX(id) FROM orcamentos))
SELECT setval(pg_get_serial_sequence('itens_orcamento',   'id'), (SELECT MAX(id) FROM itens_orcamento))
SELECT setval(pg_get_serial_sequence('alertas',           'id'), (SELECT MAX(id) FROM alertas))
SELECT setval(pg_get_serial_sequence('manutencoes',       'id'), (SELECT MAX(id) FROM manutencoes))

COMMIT
